### ISSUE TITLE
support and title

### ISSUE THREAD

**Issue by alpul9** [gergelykalman/torspray#1]
hi bro, nice soft!
you need support in btc\monero?

improve installation instruction:
node-exec \ cluster-exec - this command not found
correct command on this moment:
run \ run-all

**Comment by gergelykalman** [comment]
Thanks, I pushed a fix for this. This whole thing will eventually be a part of pynfra (https://github.com/gergelykalman/pynfra), but I did not have much time to make progress on that lately.

Partly as a result of that I accidentally committed some test creds, which I had to nuke with force push. Sorry about that, don't code before coffee.

Speaking of coffee, I set this up in case you were serious: https://www.buymeacoffee.com/gergelykalman
